// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: blacklist.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createBlacklistDom = `-- name: CreateBlacklistDom :one
INSERT INTO blacklist (id, name)
VALUES (
    $1,
    $2
)
RETURNING id, created_at, name
`

type CreateBlacklistDomParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateBlacklistDom(ctx context.Context, arg CreateBlacklistDomParams) (Blacklist, error) {
	row := q.db.QueryRowContext(ctx, createBlacklistDom, arg.ID, arg.Name)
	var i Blacklist
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Name)
	return i, err
}

const deleteBlacklistDom = `-- name: DeleteBlacklistDom :exec
DELETE FROM blacklist WHERE name = $1
`

func (q *Queries) DeleteBlacklistDom(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteBlacklistDom, name)
	return err
}

const deleteBlacklistDoms = `-- name: DeleteBlacklistDoms :exec
DELETE FROM blacklist
`

func (q *Queries) DeleteBlacklistDoms(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteBlacklistDoms)
	return err
}

const getBlacklistDom = `-- name: GetBlacklistDom :one
SELECT id, created_at, expires_at, name FROM whitelist WHERE name = $1
`

func (q *Queries) GetBlacklistDom(ctx context.Context, name string) (Whitelist, error) {
	row := q.db.QueryRowContext(ctx, getBlacklistDom, name)
	var i Whitelist
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Name,
	)
	return i, err
}

const getBlacklistDoms = `-- name: GetBlacklistDoms :many
SELECT id, created_at, name FROM blacklist
`

func (q *Queries) GetBlacklistDoms(ctx context.Context) ([]Blacklist, error) {
	rows, err := q.db.QueryContext(ctx, getBlacklistDoms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blacklist
	for rows.Next() {
		var i Blacklist
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
