// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Domain struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	IsBlocked bool
}

type Whitelist struct {
	ID        uuid.UUID
	CreatedAt time.Time
	ExpiresAt sql.NullTime
	Name      string
}
