// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: whitelist.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createWhitelistDom = `-- name: CreateWhitelistDom :one
INSERT INTO whitelist (id, name)
VALUES (
    $1,
    $2
)
RETURNING id, created_at, expires_at, name
`

type CreateWhitelistDomParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateWhitelistDom(ctx context.Context, arg CreateWhitelistDomParams) (Whitelist, error) {
	row := q.db.QueryRowContext(ctx, createWhitelistDom, arg.ID, arg.Name)
	var i Whitelist
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Name,
	)
	return i, err
}

const createWhitelistDomTemp = `-- name: CreateWhitelistDomTemp :one
INSERT INTO whitelist (id, expires_at, name)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, created_at, expires_at, name
`

type CreateWhitelistDomTempParams struct {
	ID        uuid.UUID
	ExpiresAt sql.NullTime
	Name      string
}

func (q *Queries) CreateWhitelistDomTemp(ctx context.Context, arg CreateWhitelistDomTempParams) (Whitelist, error) {
	row := q.db.QueryRowContext(ctx, createWhitelistDomTemp, arg.ID, arg.ExpiresAt, arg.Name)
	var i Whitelist
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Name,
	)
	return i, err
}

const deleteWhitelistDom = `-- name: DeleteWhitelistDom :exec
DELETE FROM whitelist WHERE name = $1
`

func (q *Queries) DeleteWhitelistDom(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteWhitelistDom, name)
	return err
}

const deleteWhitelistDoms = `-- name: DeleteWhitelistDoms :exec
DELETE FROM whitelist
`

func (q *Queries) DeleteWhitelistDoms(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteWhitelistDoms)
	return err
}

const deleteWhitelistTempDoms = `-- name: DeleteWhitelistTempDoms :exec
DELETE FROM whitelist WHERE expires_at IS NOT NULL AND expires_at <= now()
`

func (q *Queries) DeleteWhitelistTempDoms(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteWhitelistTempDoms)
	return err
}

const getWhitelistDom = `-- name: GetWhitelistDom :one
SELECT id, created_at, expires_at, name FROM whitelist WHERE name = $1 AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetWhitelistDom(ctx context.Context, name string) (Whitelist, error) {
	row := q.db.QueryRowContext(ctx, getWhitelistDom, name)
	var i Whitelist
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Name,
	)
	return i, err
}

const getWhitelistDoms = `-- name: GetWhitelistDoms :many
SELECT id, created_at, expires_at, name FROM whitelist
`

func (q *Queries) GetWhitelistDoms(ctx context.Context) ([]Whitelist, error) {
	rows, err := q.db.QueryContext(ctx, getWhitelistDoms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Whitelist
	for rows.Next() {
		var i Whitelist
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
